name: Сообщить о проблеме
description: Создать новый отчет о проблеме
title: ""
labels: "bug"
body:
- type: input
  attributes:
    label: Версия приложения
    description: С какой версией приложения возникла проблема?
    placeholder: 21.5.1
  validations:
    required: true
- type: textarea
  attributes:
    label: Описание проблемы
    description: Подробно опишите суть возникшей проблемы, что не работает и как по вашему должно было работать. Добавите скришноты если необходимо
  validations:
    required: true
- type: input
  attributes:
    label: Как воспроизвести
    description: Опишите пошагово как воспроизвести эту проблему
    placeholder: Откройте "...", затем перейтиде в "..." и увидите ошибку "..."
