name: Bug Report
description: Report an Electron bug
title: "[Bug]: "
labels: "bug :beetle:"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
      - label: I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
        required: true
- type: input
  attributes:
    label: Electron Version
    description: What version of Electron are you using?
    placeholder: 12.0.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
